name: Deploy to Production

on:
  schedule:
  - cron: '5-59/10 * * * *'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Deploy to production
      run: echo 'Deploying to production...'
